from typing import Protocol


class UIProtocol(Protocol):
    def post_message(self, role: str, text: str) -> None: ...

    def set_status(self, text: str) -> None: ...

    def clear_status(self) -> None: ...

    def get_approval(self, prompt: str) -> bool: ...
