# name: hello-cluster
# description: Ping the cluster node group.
# target: cluster
# requires_approval: true
# tags:
#   - connectivity
#   - cluster

- hosts: cluster
  become: yes
  tasks:
    - name: Ping
      ping:
